# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobe',
            name='id',
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='image',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False, unique=True),
        ),
    ]
