# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160219_1739'),
        ('closet', '0002_auto_20160219_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinationName', models.CharField(max_length=50, null=True)),
                ('trend', models.CharField(max_length=2000, null=True)),
                ('topLink', models.CharField(max_length=2000, null=True)),
                ('bottomLink', models.CharField(max_length=2000, null=True)),
                ('footLink', models.CharField(max_length=2000, null=True)),
                ('accLink', models.CharField(max_length=2000, null=True)),
                ('access', models.IntegerField()),
                ('fbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.fbUser')),
            ],
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='image',
            field=models.CharField(max_length=3000, primary_key=True, serialize=False, unique=True),
        ),
    ]
