# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_combination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
