# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_auto_20160220_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobe',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
