# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_auto_20160220_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True, unique=True),
        ),
    ]
