# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160219_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='fbuser',
            name='fbid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
