# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20160219_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.fbUser')),
                ('friend', models.ManyToManyField(related_name='friendOfUser', to='login.fbUser')),
            ],
        ),
    ]
