# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.CharField(default=datetime.datetime(2016, 2, 20, 2, 44, 36, 972485, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
