# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160219_1739'),
        ('friend', '0002_auto_20160220_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(related_name='friendOfUser', to='login.fbUser'),
        ),
    ]
